// Generated by CoffeeScript 1.6.1
(function() {
  var app, express, fs, http, io, server;

  express = require('express');

  app = express();

  http = require('http');

  fs = require('fs');

  app.use('/static', express["static"](__dirname + '/static'));

  server = http.createServer(app);

  server.listen(4000);

  io = require('socket.io').listen(server);

  app.get('/', function(req, res) {
    return fs.createReadStream('./views/index.html').pipe(res);
  });

  io.sockets.on('connection', function(socket) {
    console.log("Client connected");
    socket.on('note_on', function(note) {
      return socket.broadcast.emit('note_on', note);
    });
    return socket.on('note_off', function(note) {
      return socket.broadcast.emit('note_off', note);
    });
  });

}).call(this);
