// Generated by CoffeeScript 1.6.1
(function() {
  var MIDIUtil, test;

  test = require('tap').test;

  MIDIUtil = require('../server.js').MIDIUtil;

  test("Ensure that MIDI conversion works OK.", function(t) {
    var cg, mu,
      _this = this;
    mu = new MIDIUtil;
    cg = new ChordGenerator;
    t.test("Ensure that note resolution works.", function(t) {
      t.equal(mu.midiToNoteName(60), "C");
      t.equal(mu.midiToNoteName(79), "G");
      t.equal(mu.midiToNoteName(82), "Bb");
      return t.end();
    });
    t.end();
    return t.test("Ensure root offset works.", function(t) {
      t.equal(mu.offsetFromRoot("C", "C"), 0);
      t.equal(mu.offsetFromRoot("C", "D"), 2);
      t.equal(mu.offsetFromRoot("C", "F#"), 6);
      t.equal(mu.offsetFromRoot("A", "D"), 5);
      return t.end();
    });
  });

}).call(this);
